# Generated by Django 4.0.5 on 2022-06-28 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autosearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchoption',
            old_name='address',
            new_name='searched',
        ),
    ]
